### ISSUE TITLE
Option to force delete read-only duplicates

### ISSUE THREAD

**Issue by necros2k7** [qarmin/czkawka#1647]
subj

**Comment by qarmin** [comment]
On which OS?
On linux I can easily remove read-only files(not sure if this is my config, or config of most linux distros)

**Comment by necros2k7** [comment]
on Windows

**Comment by qarmin** [comment]
https://github.com/rust-lang/rust/pull/134679 - this was fixed in rust and will be available in next version

**Comment by HotshotGT** [comment]
This still appears to be a problem on Windows with the Krokiet release from yesterday.
