### ISSUE TITLE
3.10 fails to start on Windows 10

### ISSUE THREAD

**Issue by penyuan** [qarmin/czkawka#330]
Hello,

I downloaded the latest Windows build of 3.10, but it fails to start on my Windows 10 system with an error dialog: 

Dialog title: "windows_czkawka_gui.exe - Application Error"

Message:

"The exception Breakpoint
A breakpoint has been reached.
(0x80000003) occurred in the application at location 0x00007FFF7035E152.

Click OK to terminate the program"

How can this problem be fixed?

**Comment by qarmin** [comment]
Can you run it from Powershell to get more detailed log?
I think that it may Windows bug, since I tested it on virtual machine and it worked fine.

**Comment by penyuan** [comment]
Hi @qarmin, I just tried running 3.10 from Powershell but there wasn't any output in Powershell and I just got the same error dialog... Anything else I can check?

**Comment by poisonborz** [comment]
The problem is probably more specific, I can run the gui without problems (build 19041)

**Comment by penyuan** [comment]
By the way, it runs fine in my Windows 7 SP1 virtual machine. However, I still get that error when starting Czkawka in my Windows 10 system. Anything else I can check?

**Comment by penyuan** [comment]
> Apparently the failure to start happens when the application's folder resides in a path which contains a folder named 'bin'. The same crash happens with the previous release too. Weird...

I can confirm @varverd's observation. Once I moved the program to a path without "bin" in the path it opened!

This sounds like an important clue. Any idea what might be causing the problem?

**Comment by Elaborendum** [comment]
I don't know if I should open a new issue, but I installed 3.3.1 with Chocolatey and I can't open it either. Win10 too.

**Comment by varverd** [comment]
@Elaborendum, the issue still exists on the as of now current version, 4.0.0. Just make sure the application's folder does not reside in a path which contains a folder named 'bin'.

**Comment by Elaborendum** [comment]
@varverd There's no "bin" in the path to the application. But, one of the folders in the path is right next to a "bin" folder. Additionally, Chocolatey created a shim that does reside in a "bin" folder. Could any of these be causing the problem, then?

If so, can I just move the .exe file, or do I have to move the entire folder? (I'm worried the second option could mess with Chocolatey)

**Comment by varverd** [comment]
@Elaborendum, it might indeed be that 'bin' folder for the shim. I don't use Chocolatey, so am unable to test.
I suggest you give the normal version a try (windows_czkawka_gui.zip). It doesn't need installing; just unzip and run. Mine's located at 'c:\tmp\czkawka\'.
Uninstall the one from Chocolatey, since it doesn't work.

**Comment by github-account1111** [comment]
> Apparently the failure to start happens when the application's folder resides in a path which contains a folder named 'bin'. The same crash happens with the previous release too. Weird...

OMG thanks so much.
What are the chances?
I put all the portable applications into a bin folder on a separate partition and was completely lost as to why nothing was happening.

**Comment by matqua** [comment]
I came here to say the same. Had this working OK on Linux, but wanted to run it on my faster M1 Mac. Lost hours in trying to get it to run, trying to compile it from source, get rust to try and recognise the apple Foundation framework. 

Thought stuff it, I give up and got my work Windows machine. Extracted the zip to my userfolder\bin\czkawka and of course it wouldn't work. No error, nothing. Tried at the console, again no error, no message, ziltch. 

Random googling just to see if I am loosing my mind or if there is something else at play here and I come across this issue.

Can I assist with troubleshooting this issue by collecting any logs or something to assist?

**Comment by qarmin** [comment]
This is GDB backtrace, I have no idea what cause problem
```
(czkawka_gui.exe:384): Gdk-WARNING **: 16:25:18.961: Failed to get device node p
roperty {78C34FC8-104A-4ACA-9EA4-524D52996E57},256 size: Element not found.

(czkawka_gui.exe:384): Gdk-WARNING **: 16:25:18.979: Failed to get device node p
roperty {78C34FC8-104A-4ACA-9EA4-524D52996E57},256 size: Element not found.

(czkawka_gui.exe:384): Gtk-WARNING **: 16:25:19.948: Could not load a pixbuf fro
m /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk+-3.24.22/gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: asse
rtion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/
image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk+-3.24.22/gtk/gtkiconhelper.c:494:ensure_surface_for_g
icon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x
16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-qu
ark, 3)

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x0000000170055af5 in DbgBreakPoint () from C:\windows\system32\ntdll.dll
(gdb) backtrae
Undefined command: "backtrae".  Try "help".
(gdb) backtrace
#0  0x0000000170055af5 in DbgBreakPoint () from C:\windows\system32\ntdll.dll
#1  0x0000000064a35cda in ?? ()

```

**Comment by qarmin** [comment]
Found this one - https://gitlab.gnome.org/GNOME/gtk/-/issues/4040
Looks that this is fixed in recent GTK version(probably GTK 4.4/4.6)

**Comment by varverd** [comment]
It still crashes when there's a folder named 'bin' anywhere in the installation's path. No message shown; I see on task manager it starts and just dies after a few moments.
I tried both windows_czkawka_gui_46.zip and windows_czkawka_gui_412.zip ( Version 9.0.0 - 16.03.2025r, https://github.com/qarmin/czkawka/releases/tag/9.0.0 )
windows_czkawka_gui_412.zip crashes upon trying to start irrespective of the folder path, on Windows 11 Pro, whereas windows_czkawka_gui_46.zip works fine.
Just FYI, no real big deal, since one can simply avoid using a folder named 'bin'. Still weird, but only mild annoyance I'd say. 
Thank you for the new version.
Kind regards

**Comment by qarmin** [comment]
Version 9.0.0 does not contain a potential fix for this issue.
Could you check if the binaries from https://github.com/qarmin/czkawka/releases/tag/Nightly resolve the problem?

**Comment by varverd** [comment]
Oh, I misunderstood the completion of this very issue ( #330 ) as having resolved the crashing issue. My bad.
I've just tested with the nightly builds as you suggested, and the result is exactly the same as mentioned above ( https://github.com/qarmin/czkawka/issues/330#issuecomment-3090728091 ).
Kind regards

**Comment by qarmin** [comment]
GTK frontend version 12.0 will be the last release and will no longer be actively maintained. Only critical issues affecting unofficial Docker and Debian packages may still be addressed. All GTK-specific issues will be closed. Please use Krokiet as the recommended replacement, as it is actively maintained and more reliable.
