### ISSUE TITLE
Cannot symlink or hardlink: can only delete dupes

### ISSUE THREAD

**Issue by Rings4** [qarmin/czkawka#373]
Scanned 2 directories, clicked "select all except oldest", then clicked hardlink: nothing happened. Symlink didn't do anything either. Delete works, but I don't want to delete.

**Comment by NAHNAH55** [comment]
Same issue. Symlink function does nothing. I wish I knew this before spending all day scanning my files.

**Comment by qarmin** [comment]
What OS?
If windows, then for now only simlinks are implemented.
For unix like os(which use inode like Linux or macOS) it should work both symlink and hardlink

**Comment by NAHNAH55** [comment]
Win 10. I haven't tried hard links, but symlinks don't work. I've tried both elevated and not elevated access. I select an option, press the symlink button and the files are deselected. No change takes place, neither file has been replaced with a link.

**Comment by Rings4** [comment]
dupeGuru works with symlinks and hardlinks just fine. Perhaps you can look at what they're doing to implement into your own software? https://dupeguru.voltaicideas.net/

**Comment by qarmin** [comment]
The problem is mostly with functions which Rust standard library provide(Rust and Python differs a lot)
Symlink on Windows problem should be fixed by https://github.com/qarmin/czkawka/pull/409

**Comment by qarmin** [comment]
Hard-links should probably works with the latest version(future 3.2 version)

**Comment by mascherone108** [comment]
I'm using Kubuntu 21.04 and it still doesn't work for me just as OP described.

**Comment by qarmin** [comment]
Oh, now I understand what is happening(I think that this behavior is somewhere documented).

Symlinks and Hardlinks can be generated only if in group is at least 2 selected results.
1 result is always unchanged and second and furthers are hardlinked to first.

I reopened issue because in future I probably can implement this(this require to do some deep changes in method how hardlinks or symlinks are handled)

**Comment by Bartek200219** [comment]
When I try to create hard link program crashes.
(Czkawka 3.2.0
Windows 10 2004)

**Comment by qarmin** [comment]
Crash when hardlinking is fixed in master branch, but still happens with 3.3.1 version and it show when clicking at hardlink/symlink button without any record selected.

Warning message about it is added in this PR - https://github.com/qarmin/czkawka/pull/489

For now I don't see simple and clear for user method to set target of file used in hardlinking

**Comment by z0diaq** [comment]
What about drag and drop within groups to change ordering ?

**Comment by z0diaq** [comment]
Also current behavior is very non intuitive - I've also spent some time trying to figure out how to use symlink \ hardlink... Same as author of topic I've thought I should choose single file and other files from group will point to it... was quite lost after clicking hardlink \ softlink and nothing happened - 'these buttons work at all?' and started to search on web for and found this thread...

Would be great if You could spend some time on improving current behavior, what I could suggest these approaches to consider:
- r-click and select 'make primary' to select which stays and which will be changed to link
- allow to drag and drop within group to change ordering
- also disable or at least show error message when user selects single item and clicks any of link buttons
- please don't remove items from list if operation fails - for example hardlink may fail but softlink may pass - had exactly this issue today, had to scan again to restore found dups

**Comment by login404** [comment]
Creating hard links can not work, showing refusal access
But the symbolic link can work properly
dupeGuru hard links and symbolic links can work properly
The test results on Windows 7 and windows 10 21h2 (19044.1415) are the same

![1](https://user-images.githubusercontent.com/69505914/150606558-92dcf176-93c3-4840-b80a-34846ad81f90.gif)
